apiVersion: v1
kind: Deployment
metadata:
  name: maratona-deployment
spec:
  replicas: 5
  selector: ## para modificar os pods que jรก estiverem no ar
    matchLabels:
      app: pods-deployment
  template:
    metadata:
      labels: 
        app: pods-deployment
    spec:
      containers:
      - name: servidor-nginxs
        image: nginx:1.17-alpine
        ports:
        - containerPor: 80
